#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wclean $targetType twoPhaseMixture
wclean $targetType interfaceProperties
wclean $targetType twoPhaseProperties
wclean $targetType incompressible
wclean $targetType compressible
wclean $targetType immiscibleIncompressibleTwoPhaseMixture

#------------------------------------------------------------------------------
